# Generated by Django 4.1.3 on 2023-03-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='short_intro',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
