# Generated by Django 4.1.3 on 2023-03-17 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_suggestion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suggestion',
        ),
    ]
