# Generated by Django 4.1.5 on 2023-01-26 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Column',
            new_name='Table',
        ),
    ]
