# Generated by Django 4.1.3 on 2023-01-27 15:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_rename_column_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='total',
        ),
        migrations.AlterField(
            model_name='table',
            name='col1',
            field=models.TextField(blank=True, null=True, verbose_name='Column 1'),
        ),
        migrations.AlterField(
            model_name='table',
            name='col2',
            field=models.TextField(blank=True, null=True, verbose_name='Column 2'),
        ),
        migrations.AlterField(
            model_name='table',
            name='col3',
            field=models.TextField(blank=True, null=True, verbose_name='Column 3'),
        ),
        migrations.AlterField(
            model_name='table',
            name='col4',
            field=models.TextField(blank=True, null=True, verbose_name='Column 4'),
        ),
        migrations.AlterField(
            model_name='table',
            name='col5',
            field=models.TextField(blank=True, null=True, verbose_name='Column 5'),
        ),
        migrations.AlterField(
            model_name='table',
            name='date',
            field=models.DateField(verbose_name='Date (yyyy-mm-dd)'),
        ),
        migrations.AlterField(
            model_name='table',
            name='title',
            field=models.TextField(verbose_name='Title of the table'),
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('col1', models.TextField(blank=True, null=True, verbose_name='Column 1 entry')),
                ('col2', models.TextField(blank=True, null=True, verbose_name='Column 2 entry')),
                ('col3', models.TextField(blank=True, null=True, verbose_name='Column 3 entry')),
                ('col4', models.TextField(blank=True, null=True, verbose_name='Column 4 entry')),
                ('col5', models.TextField(blank=True, null=True, verbose_name='Column 5 entry')),
                ('date', models.DateField(verbose_name='Date (yyyy-mm-dd)')),
                ('total', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.table')),
            ],
        ),
    ]
