# Generated by Django 4.1.3 on 2023-01-27 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_remove_table_total_alter_table_col1_alter_table_col2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='date',
        ),
    ]
