# Generated by Django 4.1.3 on 2023-01-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_remove_table_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
