# Generated by Django 4.1.3 on 2023-01-31 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0007_rename_columns_table_column'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='column',
        ),
        migrations.AddField(
            model_name='column',
            name='table_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tables.table'),
        ),
    ]
