# Generated by Django 4.1.3 on 2023-01-31 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0008_remove_table_column_column_table_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='total',
        ),
        migrations.AddField(
            model_name='table',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
