# Generated by Django 4.1.3 on 2023-01-31 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0009_remove_column_total_table_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
