# Generated by Django 4.1.3 on 2023-01-31 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0010_alter_table_total'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Column',
            new_name='Row',
        ),
    ]
