# Generated by Django 4.1.3 on 2023-02-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0011_rename_column_row'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date (yyyy-mm-dd)'),
        ),
    ]
