# Generated by Django 4.1.3 on 2023-02-28 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0012_alter_row_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='row',
            options={'ordering': ['date', 'col1', 'col2', 'col3', 'col4', 'col5', '-created']},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['-title', '-created']},
        ),
    ]
