# Generated by Django 4.1.3 on 2023-02-28 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_id'),
        ('tables', '0013_alter_row_options_alter_table_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='row',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
