# Generated by Django 4.1.3 on 2023-02-28 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_id'),
        ('tables', '0014_row_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='row',
            name='owner',
        ),
        migrations.AddField(
            model_name='table',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
