# Generated by Django 4.1.3 on 2023-02-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0015_remove_row_owner_table_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date (yyyy-mm-dd)'),
        ),
    ]
