# Generated by Django 4.1.3 on 2023-03-17 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0018_table_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='value',
            new_name='status',
        ),
    ]
