# Generated by Django 4.1.3 on 2023-03-17 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0021_rename_table_suggestion_table_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suggestion',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='is_read',
        ),
        migrations.AddField(
            model_name='suggestion',
            name='row',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tables.row'),
        ),
    ]
