# Generated by Django 4.1.3 on 2023-03-17 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0022_alter_suggestion_options_remove_suggestion_is_read_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='row',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tables.row'),
        ),
    ]
