# Generated by Django 4.1.3 on 2023-03-17 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0023_alter_suggestion_row'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestion',
            old_name='row',
            new_name='rows',
        ),
    ]
