# Generated by Django 4.1.3 on 2023-03-17 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0025_remove_suggestion_rows_suggestion_rows'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suggestion',
        ),
    ]
