# Generated by Django 4.1.3 on 2023-03-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0027_sugestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='sugestion',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
