# Generated by Django 4.1.3 on 2023-03-17 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_delete_suggestion'),
        ('tables', '0028_sugestion_is_read'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sugestion',
            new_name='Suggestion',
        ),
    ]
