# Generated by Django 4.1.3 on 2023-03-17 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0029_rename_sugestion_suggestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='table_name',
        ),
        migrations.AddField(
            model_name='suggestion',
            name='row',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tables.row'),
        ),
    ]
