# Generated by Django 4.1.3 on 2023-03-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0030_remove_suggestion_table_name_suggestion_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='col1',
            field=models.TextField(blank=True, null=True, verbose_name='Column 1'),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='col2',
            field=models.TextField(blank=True, null=True, verbose_name='Column 2'),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='col3',
            field=models.TextField(blank=True, null=True, verbose_name='Column 3'),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='col4',
            field=models.TextField(blank=True, null=True, verbose_name='Column 4'),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='col5',
            field=models.TextField(blank=True, null=True, verbose_name='Column 5'),
        ),
    ]
