# Generated by Django 4.1.3 on 2023-03-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0032_remove_suggestion_row_suggestion_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='row',
            name='table_name',
        ),
        migrations.AddField(
            model_name='suggestion',
            name='row',
            field=models.ManyToManyField(blank=True, to='tables.row'),
        ),
        migrations.AddField(
            model_name='table',
            name='row',
            field=models.ManyToManyField(blank=True, to='tables.row'),
        ),
    ]
