# Generated by Django 4.1.3 on 2023-03-17 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0033_remove_row_table_name_suggestion_row_table_row'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='row',
            new_name='rows',
        ),
    ]
