# Generated by Django 4.1.3 on 2023-03-19 06:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0035_remove_suggestion_row_remove_table_rows_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suggestion',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='suggestion',
            old_name='table',
            new_name='table_name',
        ),
        migrations.AddField(
            model_name='suggestion',
            name='total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='Sug_row',
            fields=[
                ('col1', models.TextField(blank=True, null=True, verbose_name='Column 1 entry')),
                ('col2', models.TextField(blank=True, null=True, verbose_name='Column 2 entry')),
                ('col3', models.TextField(blank=True, null=True, verbose_name='Column 3 entry')),
                ('col4', models.TextField(blank=True, null=True, verbose_name='Column 4 entry')),
                ('col5', models.TextField(blank=True, null=True, verbose_name='Column 5 entry')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date (yyyy-mm-dd)')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sug_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tables.suggestion')),
            ],
        ),
    ]
