# Generated by Django 4.1.3 on 2023-03-19 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0036_alter_suggestion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sug_row',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
