# Generated by Django 4.1.3 on 2023-03-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0037_sug_row_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sug_row',
            name='desc',
        ),
        migrations.AddField(
            model_name='suggestion',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
