# Generated by Django 4.1.3 on 2023-03-19 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0038_remove_sug_row_desc_suggestion_desc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sug_row',
            new_name='Sugrow',
        ),
    ]
